---
- name: Install Developer Tools
  pacman:
    name: '{{ developer_stack }}'
    state: present
  become_user: 'root'
  become: yes

- name: Install Developer Tools from Arch User Repository
  yay:
    name: '{{ developer_stack_yay }}'
    state: present
  become: yes
  tags:
    - yay

- name: Install Docker Tools
  include: ../../general/docker-config.yml

- name: Test commands
  script: test_commands.sh
