---
- name: Install Developer Tools
  pacman:
    name: '{{ developer_stack + developer_stack_arch }}'
    state: present
  become: yes
  when: ansible_distribution == 'Archlinux'

- name: Install Developer Tools [Ubuntu]
  apt:
    name: '{{ developer_stack + developer_stack_ubuntu }}'
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install Developer Tools from AUR
  yay:
    name: '{{ developer_stack_yay }}'
    state: present
  become: yes
  tags: yay
  when: ansible_distribution == 'Archlinux'

- name: Install Developer Tools from Snap [Ubuntu]
  snap:
    name: '{{ developer_stack_snap }}'
    state: present
    # This option can only be specified if there is a single snap in the task.!?
    classic: true
  become: yes
  tags: snap
  when: ansible_distribution == 'Ubuntu'

- name: Setup Docker Tools
  include: ../../general/docker-config.yml

- name: Create output directory
  file:
    path: "{{ output_dir }}"
    state: directory
  become_user: '{{ run_as_user }}'
  tags: test
- name: Read prev test results
  shell: cat {{ output_dir }}/dev_test_result.txt
  register: prev_test_result
  become_user: "{{run_as_user}}"
  changed_when: false
  ignore_errors: yes
  tags: test
- name: Test commands
  script: test_commands.sh 2>&1 tee {{ output_dir }}/dev_test_result.txt
  become_user: "{{run_as_user}}"
  register: test_result
  changed_when: (prev_test_result.stdout is undefined or test_result.stdout is undefined) or test_result.stdout != prev_test_result.stdout
  tags: test
