---
- name: Install apps
  pacman:
    name: '{{ apps }}'
    state: present
  become: yes
  when: ansible_distribution == 'Archlinux' and not no_ui_present

- name: Install apps [Ubuntu]
  snap:
    name: '{{ apps_snap }}'
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu' and not no_ui_present

- name: Install apps from AUR
  yay:
    name: '{{ apps_yay }}'
    state: present
  become: yes
  when: ansible_distribution == 'Archlinux' and not no_ui_present