install:
  apt:
  - zsh
  - git
  - curl
  - wget
  - p7zip
  - vim
  - htop
  - mc
  - tree
  - xclip
  - nano
  - util-linux
  - rmlint
  - gparted
  - net-tools
  - borgbackup
  - git-extras
  - build-essential
  - python3-pip
  - python3-dev
  - python3-setuptools
  - default-jre
  - openjdk-8-jre-headless
  - openjdk-8-jdk
  - openjdk-11-jre-headless
  - openjdk-11-jdk
  - firefox
  - meld
  - vlc
  - gimp
  - imagemagick
  - inkscape
  - peek
  - blender
  - nodejs
  - npm
  - maven
  - docker
  - docker-compose
  - virtualbox
  - vagrant
  - cmake
  - gdb
  - clang
  - lldb
  - valgrind
  - ninja-build
  - nim
  - jq
  - sqlcipher
  aur:
  - git-extras
  - visual-studio-code-bin
  - google-chrome
  - nomachine
  - whatsapp
  - drawio-desktop
  - mqtt-cli-bin
  - android-studio
  - android-sdk
  - android-sdk-build-tools
  - android-sdk-platform-tools
  - android-sdk-cmdline-tools-latest
  - android-platform
  - android-emulator
  brew:
  - zsh
  - git
  - curl
  - wget
  - p7zip
  - vim
  - htop
  - mc
  - tree
  - xclip
  - nano
  - util-linux
  - rmlint
  - borgbackup
  - git-extras
  - python
  - imagemagick
  - gh
  - nodejs
  - npm
  - maven
  - docker
  - docker-compose
  - cmake
  - ninja
  - emscripten
  - go
  - golang
  - nim
  - jq
  - sqlcipher
  brew_cask:
  - visual-studio-code
  - firefox
  - google-chrome
  - brave-browser
  - meld
  - vlc
  - gimp
  - inkscape
  - discord
  - whatsapp
  - openvpn-connect
  - ultimaker-cura
  - blender
  - drawio
  brew_tap:
  - cask: adoptopenjdk
    tap: adoptopenjdk/openjdk
  - cask: mqtt-cli
    tap: hivemq/mqtt-cli
  choco:
  - javaruntime
  - firefox
  - google-chrome
  - brave
  - meld
  - vlc
  - gimp
  - imagemagick
  - inkscape
  - nomachine
  - discord
  - whatsapp
  - openvpn-connect
  - blender
  - nodejs
  - npm
  - maven
  - dbeaver
  - virtualbox
  - vagrant
  - cmake
  - gdb
  - clang
  - lldb
  - valgrind
  - golang
  - golang
  - nim
  custom_apt:
  - key: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    name: brave
    repo: deb https://brave-browser-apt-release.s3.brave.com/ stable main
  - key: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    name: gh
    repo: deb https://cli.github.com/packages stable main
  deb:
  - https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
  - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - https://download.nomachine.com/download/7.8/Linux/nomachine_7.8.2_1_amd64.deb
  - https://discord.com/api/download?platform=linux&format=deb
  - https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
  pacman:
  - zsh
  - git
  - curl
  - wget
  - p7zip
  - vim
  - htop
  - mc
  - tree
  - xclip
  - nano
  - util-linux
  - rmlint
  - gparted
  - net-tools
  - nano-syntax-highlighting
  - borg
  - yay
  - base-devel
  - python-pip
  - python-setuptools
  - jre-openjdk
  - jre8-openjdk-headless
  - jdk8-openjdk
  - jre11-openjdk-headless
  - jdk11-openjdk
  - firefox
  - meld
  - vlc
  - gimp
  - imagemagick
  - inkscape
  - peek
  - discord
  - cura
  - blender
  - github-cli
  - nodejs
  - npm
  - maven
  - docker
  - docker-compose
  - dbeaver
  - virtualbox
  - vagrant
  - cmake
  - gdb
  - clang
  - lldb
  - valgrind
  - ninja
  - emscripten
  - go
  - go-tools
  - nim
  - jq
  - sqlcipher
  pip:
  - thefuck
  - setuptools
  - jupyterlab
  - conan
  snap:
  - cura-slicer
  - drawio
uninstall:
  apt:
  - hub
  brew:
  - hub
  choco:
  - hub
  pacman:
  - hub
