install:
  apt:
  - zsh
  - git
  - curl
  - wget
  - p7zip
  - vim
  - htop
  - mc
  - tree
  - xclip
  - nano
  - util-linux
  - rmlint
  - gparted
  - net-tools
  - borgbackup
  - git-extras
  - build-essential
  - python3-pip
  - python3-dev
  - python3-setuptools
  - java
  - openjdk-8-jre-headless
  - openjdk-8-jdk
  - openjdk-11-jre-headless
  - openjdk-11-jdk
  - nodejs
  - npm
  - maven
  - docker
  - docker-compose
  - cmake
  - gdb
  - clang
  - lldb
  - valgrind
  - ninja-build
  - nim
  aur:
  - git-extras
  - visual-studio-code-bin
  - mqtt-cli-bin
  brew:
  - zsh
  - git
  - curl
  - wget
  - p7zip
  - vim
  - htop
  - mc
  - tree
  - xclip
  - nano
  - util-linux
  - rmlint
  - borgbackup
  - git-extras
  - python
  - java
  - gh
  - nodejs
  - npm
  - maven
  - docker
  - docker-compose
  - cmake
  - ninja
  - emscripten
  - go
  - golang
  - nim
  brew_cask:
  - visual-studio-code
  brew_tap:
  - cask: mqtt-cli
    tap: hivemq/mqtt-cli
  choco:
  - java
  - nodejs
  - npm
  - maven
  - cmake
  - gdb
  - clang
  - lldb
  - valgrind
  - golang
  - golang
  - nim
  custom_apt:
  - key: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    name: gh
    repo: deb https://cli.github.com/packages stable main
  deb:
  - https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
  pacman:
  - zsh
  - git
  - curl
  - wget
  - p7zip
  - vim
  - htop
  - mc
  - tree
  - xclip
  - nano
  - util-linux
  - rmlint
  - gparted
  - net-tools
  - nano-syntax-highlighting
  - borg
  - base-devel
  - python-pip
  - python-setuptools
  - java
  - jre8-openjdk-headless
  - jdk8-openjdk
  - jre11-openjdk-headless
  - jdk11-openjdk
  - github-cli
  - nodejs
  - npm
  - maven
  - docker
  - docker-compose
  - cmake
  - gdb
  - clang
  - lldb
  - valgrind
  - ninja
  - emscripten
  - go
  - go-tools
  - nim
  pip:
  - thefuck
  - setuptools
  - jupyterlab
  - conan
uninstall:
  apt:
  - hub
  brew:
  - hub
  choco:
  - hub
  pacman:
  - hub
