---
- name: Setup custom apt key
  apt_key:
    url: '{{ item.key }}'
    state: present
  become: yes
  loop: '{{ install.custom_apt }}'
  when: install.custom_apt is defined

- name: Setup custom apt repository
  apt_repository:
    repo: '{{ item.repo }}'
    state: present
  become: yes
  loop: '{{ install.custom_apt }}'
  when: install.custom_apt is defined

- name: Uninstall custom apt key
  apt_key:
    keyring: '{{ item.key }}'
    state: absent
  become: yes
  loop: '{{ install.custom_apt }}'
  when: uninstall.custom_apt is defined

- name: Uninstall custom apt repository
  apt_repository:
    repo: '{{ item.repo }}'
    state: absent
  become: yes
  loop: '{{ install.custom_apt }}'
  when: uninstall.custom_apt is defined

- name: Upgrade all packages [Ubuntu]
  apt:
    update_cache: yes
    force_apt_get: yes
    upgrade: dist
    cache_valid_time: 3600
  tags: upgrade

- name: Install custom apt packages
  apt:
    name: '{{ item.name }}'
    state: present
  become: yes
  loop: '{{ install.custom_apt }}'
  when: install.custom_apt is defined

- name: Uninstall custom apt packages
  apt:
    name: '{{ item.name }}'
    state: absent
  become: yes
  loop: '{{ install.custom_apt }}'
  when: install.custom_apt is defined

- name: Install Ubuntu packages
  apt:
    name: '{{ install.apt }}'
    state: present
  become: yes
  when: install.apt is defined

- name: Uninstall Ubuntu packages
  apt:
    name: '{{ uninstall.apt }}'
    state: absent
  become: yes
  when: uninstall.apt is defined

- name: Install deb packages
  apt:
    deb: '{{ item }}'
    state: present
  become: yes
  loop: '{{ install.deb }}'
  when: install.deb is defined

- name: Uninstall deb packages
  apt:
    deb: '{{ uninstall.deb }}'
    state: absent
  become: yes
  when: uninstall.deb is defined