---
- name: Install Snap packages
  snap:
    name: '{{ install.snap }}'
    state: present
    classic: yes
  become: yes
  when: install.snap is defined

- name: Uninstall Snap packages
  snap:
    name: '{{ uninstall.snap }}'
    state: absent
  become: yes
  when: uninstall.snap is defined