---
- name: Setup Docker Tools
  include_tasks: docker-config.yml

# Android
#

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

# The AUR packages install the SDK in /opt/android-sdk/. This directory has root permissions, to use it as a regular user, create the android-sdk users group, add `run_as_user`.
- name: Ensure group "android-sdk" exists
  group:
    name: android-sdk
    state: present
  when: "ansible_distribution == 'Archlinux' and 'android-sdk' in ansible_facts.packages"
- name: Add the user to android
  user:
    name: "{{ run_as_user }}"
    groups: android-sdk
    append: yes
  when: "ansible_distribution == 'Archlinux' and 'android-sdk' in ansible_facts.packages"

# Set an access control list to let user write into the android-sdk folder. As running sdkmanager can also create new files, set the ACL as default ACL. the X in the default group entry means "allow execution if executable by the owner (or anyone else)"
- name: Sets default ACL for run_as_user on /etc/foo.d/
  acl:
    path: /opt/android-sdk/
    entity: android-sdk
    etype: group
    permissions: rwx
    default: yes
    recursive: yes
    state: present
  when: "ansible_distribution == 'Archlinux' and 'android-sdk' in ansible_facts.packages"
