## Settings
# https://wiki.archlinux.org/index.php/Bash#Tab_completion
export HISTCONTROL=ignoredups

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
export HISTSIZE=100000
export HISTFILESIZE=1000000

# @nisetama and @Guss
# https://askubuntu.com/questions/67283/is-it-possible-to-make-writing-to-bash-history-immediate
export PROMPT_COMMAND="history -a;history -n;$PROMPT_COMMAND"
