# .bashrc
alias home='git --work-tree=$HOME --git-dir=$HOME/.home'

# https://stackoverflow.com/questions/9910966/how-to-get-shell-to-self-detect-using-zsh-or-bash
# .bash_profile additions
[[ -f $HOME/.human/bash_profile ]] && . $HOME/.human/bash_profile

[[ -f $HOME/.human/env_vars ]] && . $HOME/.human/env_vars
[[ -f $HOME/.human/bash-ps1.txt ]] && source $HOME/.human/bash-ps1.txt
[[ -f $HOME/.human/bash_aliases ]] && source $HOME/.human/bash_aliases
