- name: "Ubuntu workstation setup with Ansible and Git"
  hosts: localhost, test_group
  connection: local 
  become: true
  vars:
    output_dir: "/home/{{ run_as_user }}/.human/ansible/.out"

  roles:
  - { role: base,            tags: ['base'] }
  - { role: host,            tags: ['host'] }
  - { role: dev,             tags: ['dev'] }
  - { role: multimedia,      tags: ['multimedia'] }
