- name: "General workstation setup with Ansible and Git"
  hosts: localhost
  connection: local 
  become: true

  roles:
  - { role: packages,        tags: ['packages'] }
  - { role: dev,             tags: ['dev'] }