- name: "General workstation setup with Ansible and Git"
  hosts: localhost
  connection: local 
  become: true

  roles:
  - { role: base,            tags: ['base'] }
  - { role: dev,             tags: ['dev'] }
  - { role: multimedia,      tags: ['multimedia'] }
  - { role: workstation,     tags: ['workstation'] }
  - { role: optional,        tags: ['optional'] }
