- name: "General workstation setup with Ansible and Git"
  hosts: '{{ target }}'
  connection: local
  become: true

  roles:
  - { role: packages,        tags: ['packages'] }
  - { role: dev,             tags: ['dev'] }