- name: set mount list
  set_fact:
    mount_list:
      - { uuid: "ee8cb8d3-ff55-4381-9c96-ae7c3325882d", dest: "/mnt/raid", permissions: "u=rwx,g=rx,o=rx" }
      - { uuid: "5fd5ef79-fd60-4091-9273-349c0c2cad63", dest: "/mnt/quick", permissions: "u=rwx,g=rx,o=rx" }

- name: mount disks
  mount:
    path: "{{ item.dest }}"
    src: "UUID={{ item.uuid }}"
    fstype: ext4
    opts: noatime
    state: mounted
  with_items: "{{ mount_list }}"

- name: take ownership and set permissions for disk mounts  
  file:
    path: "{{ item.dest }}"
    owner: "{{ run_as_user }}"
    group: "{{ run_as_user }}"
    mode: "{{ item.permissions }}"
  with_items: "{{ mount_list }}"

- name: make dperson samba shares
  set_fact:
    dperson_samba_shares: "{{ dperson_samba_shares | default('') ~ ' -s \"' ~ item.nfs_name ~ ';/shares/' ~ item.nfs_name ~ ';yes;no;yes\"' }}"
  with_items: "{{ bind_list }}"
- name: finalize dperson samba shares
  set_fact:
    dperson_samba_shares: "{{ '-n -W -w SDHOME ' ~ dperson_samba_shares }}"
