---
- name: Checkout home-srv
  git:
    repo: 'git@github.com:stefandunca/home-srv.git'
    dest: /home/{{ run_as_user }}/services
    accept_hostkey: yes
  become_user: "{{run_as_user}}"

- name: read user group id
  shell: id -u
  register: run_as_user_uid
  become_user: "{{run_as_user}}"
  changed_when: false

- name: read user group id
  shell: id -g
  register: run_as_user_gid
  become_user: "{{run_as_user}}"
  changed_when: false

- name: 
  template:
    src: services_env.j2
    dest: /home/{{ run_as_user }}/services/.env
  become_user: "{{run_as_user}}"