FROM archlinux

ENV USER=username
ARG USER=$USER

RUN groupadd -r $USER && useradd --no-log-init -d /home/$USER/ -m -r -g $USER $USER && echo "$USER:$USER" | chpasswd

# Install prerequisities for Ansible
RUN pacman -Syyu --noconfirm --noprogressbar ansible git python-pip
RUN pacman -Syyu --noconfirm --noprogressbar zsh && rm /usr/bin/sh && ln -s /usr/bin/zsh /usr/bin/sh

# install needed dependencies
RUN pacman -Syyu --noconfirm --noprogressbar ffmpeg libxkbcommon xcb-util libxcb
RUN python3 -m pip install -r /home/$USER/.human/ansible/inventory_setup/requirements.txt

USER $USER

COPY . /home/$USER/
COPY ./.human/test/data/zshrc /home/$USER/.zshrc

# Test setup
ENTRYPOINT [ "cd $HOME && ansible-playbook -e 'ansible_python_interpreter=/usr/bin/python3' --inventory $HOME/.human/ansible/hosts.yml --limit localhost  --extra-vars '{"run_as_user":"$USER","no_ui_present":True}' $HOME/.human/ansible/test.yml" ]