FROM archlinux

ENV USER=username
ARG USER=$USERtive

RUN groupadd -r $USER && useradd --no-log-init -d /home/$USER/ -m -r -g $USER $USER && echo "$USER:$USER" | chpasswd

# Install prerequisities for Ansible
RUN pacman -Syyu --noconfirm --noprogressbar ansible git
RUN pacman -Syyu --noconfirm --noprogressbar zsh && rm /usr/bin/sh && ln -s /usr/bin/zsh /usr/bin/sh

USER $USER

COPY ....

# Test setup
ENTRYPOINT [ "cd $HOME && ansible-playbook -e 'ansible_python_interpreter=/usr/bin/python3' --inventory $HOME/.human/ansible/hosts.yml --limit localhost  --extra-vars '{"run_as_user":"$USER","no_ui_present":True}' $HOME/.human/ansible/test.yml" ]