---
- name: create the list of optional packages
  set_fact:
    local_tags: ["mobilerig"]

- name: create the list of optional packages
  set_fact:
    pacman_list:
      - { name: "xorg-xmodmap", tags: ["mobilerig"] }
      - { name: "xkeycaps", tags: ["mobilerig"] }

- name: Install pacman packages
  pacman:
    name: "{{ item.name }}"
    state: present
  become: yes
  with_items: "{{ pacman_list }}"
  when: ansible_distribution == 'Archlinux' and (item.tags | intersect(local_tags) | length == (item.tags | length))