---
- name: Install multimedia packages
  pacman:
    name: '{{ host_multimedia }}'
    state: present
  become: yes
  when: ansible_distribution == 'Archlinux' and not no_ui_present
  tags: multimedia

- name: Install multimedia packages
  apt:
    name: '{{ host_multimedia }}'
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu' and not no_ui_present
  tags: multimedia
